from __future__ import annotations

from sqlalchemy import select

from app.db.models import ObraSocial


OBRAS_SOCIALES = [
    {"codigo": "3", "nombre": "ACA SALUD"},
    {"codigo": "4", "nombre": "ACONCAGUA SALUD"},
    {"codigo": "5", "nombre": "AGUA Y ENERGIA"},
    {"codigo": "6", "nombre": "AMAC"},
    {"codigo": "7", "nombre": "AMFECOF"},
    {"codigo": "8", "nombre": "AMP"},
    {"codigo": "9", "nombre": "AMTTAC"},
    {"codigo": "10", "nombre": "ANDAR"},
    {"codigo": "11", "nombre": "APM"},
    {"codigo": "12", "nombre": "APROSS"},
    {"codigo": "13", "nombre": "PREVENCION A.R.T."},
    {"codigo": "14", "nombre": "ARISTON"},
    {"codigo": "15", "nombre": "ASAMEF"},
    {"codigo": "16", "nombre": "ATSA"},
    {"codigo": "17", "nombre": "CAJA DE ABOGADOS"},
    {"codigo": "18", "nombre": "CAJA NOTARIAL"},
    {"codigo": "19", "nombre": "CEMEC"},
    {"codigo": "20", "nombre": "CERAMISTAS"},
    {"codigo": "21", "nombre": "COBERTURA MEDICA CORDOBA"},
    {"codigo": "22", "nombre": "COLFACOR"},
    {"codigo": "23", "nombre": "COLONIA SUIZA SALUD ART"},
    {"codigo": "24", "nombre": "COMPLEMED"},
    {"codigo": "25", "nombre": "COVER SALUD"},
    {"codigo": "26", "nombre": "CPCE"},
    {"codigo": "27", "nombre": "CRS"},
    {"codigo": "28", "nombre": "DAS"},
    {"codigo": "29", "nombre": "DIBA"},
    {"codigo": "30", "nombre": "DIBPFA"},
    {"codigo": "31", "nombre": "DOCTHOS"},
    {"codigo": "32", "nombre": "DOULOS"},
    {"codigo": "33", "nombre": "MUTUAL FEDERADA SALUD"},
    {"codigo": "34", "nombre": "FIAT"},
    {"codigo": "35", "nombre": "GALENO"},
    {"codigo": "36", "nombre": "GEA"},
    {"codigo": "37", "nombre": "GEO SALUD"},
    {"codigo": "38", "nombre": "HERCULES"},
    {"codigo": "39", "nombre": "HOSPITAL PRIVADO"},
    {"codigo": "40", "nombre": "IOSE"},
    {"codigo": "41", "nombre": "ISSARA"},
    {"codigo": "42", "nombre": "JERARQUICOS"},
    {"codigo": "43", "nombre": "OSFATLYF"},
    {"codigo": "44", "nombre": "MEDICUS"},
    {"codigo": "45", "nombre": "MEDIFE"},
    {"codigo": "46", "nombre": "MET"},
    {"codigo": "47", "nombre": "NOBIS"},
    {"codigo": "48", "nombre": "OMINT"},
    {"codigo": "49", "nombre": "OSADRA"},
    {"codigo": "50", "nombre": "OSAM"},
    {"codigo": "51", "nombre": "OSDE"},
    {"codigo": "52", "nombre": "OSDIPP"},
    {"codigo": "53", "nombre": "OSDOP"},
    {"codigo": "54", "nombre": "OSECAC"},
    {"codigo": "55", "nombre": "OSIM"},
    {"codigo": "56", "nombre": "OSITAC"},
    {"codigo": "57", "nombre": "OSMATA"},
    {"codigo": "58", "nombre": "OSME"},
    {"codigo": "59", "nombre": "OSPA"},
    {"codigo": "60", "nombre": "OSPACA"},
    {"codigo": "61", "nombre": "OSPATCA"},
    {"codigo": "62", "nombre": "OSPE"},
    {"codigo": "63", "nombre": "OSPEC"},
    {"codigo": "64", "nombre": "OSPECOR"},
    {"codigo": "65", "nombre": "OSPEP"},
    {"codigo": "66", "nombre": "OSPF"},
    {"codigo": "67", "nombre": "OSPIC"},
    {"codigo": "68", "nombre": "OSPIL"},
    {"codigo": "69", "nombre": "OSPIM"},
    {"codigo": "70", "nombre": "OSPIP"},
    {"codigo": "71", "nombre": "OSPIV"},
    {"codigo": "72", "nombre": "OSPLAD"},
    {"codigo": "73", "nombre": "OSPM"},
    {"codigo": "74", "nombre": "OSPRERA"},
    {"codigo": "75", "nombre": "OSSEG"},
    {"codigo": "76", "nombre": "OSTEL"},
    {"codigo": "77", "nombre": "OSTIG"},
    {"codigo": "78", "nombre": "OSTV"},
    {"codigo": "79", "nombre": "OSYC"},
    {"codigo": "80", "nombre": "PAMI"},
    {"codigo": "81", "nombre": "PARQUE SALUD"},
    {"codigo": "82", "nombre": "PERKINS"},
    {"codigo": "83", "nombre": "PODER JUDICIAL"},
    {"codigo": "84", "nombre": "POLICIA FEDERAL"},
    {"codigo": "85", "nombre": "PREMEDICAL"},
    {"codigo": "86", "nombre": "PRENSALUD"},
    {"codigo": "87", "nombre": "RECETARIO SOLIDARIO"},
    {"codigo": "88", "nombre": "SANAR"},
    {"codigo": "89", "nombre": "SANCOR"},
    {"codigo": "90", "nombre": "VESALIO"},
    {"codigo": "91", "nombre": "VISITAR"},
    {"codigo": "92", "nombre": "VOLKSWAGEN"},
    {"codigo": "93", "nombre": "ZURICH"},
    {"codigo": "94", "nombre": "ENSALUD"},
    {"codigo": "95", "nombre": "VALESALUD"},
    {"codigo": "96", "nombre": "OSPAGA"},
    {"codigo": "97", "nombre": "BOREAL"},
    {"codigo": "98", "nombre": "COOPERATIVA HORIZONTE"},
    {"codigo": "99", "nombre": "OSCTCP"},
    {"codigo": "100", "nombre": "SWISS MEDICAL GROUP"},
    {"codigo": "101", "nombre": "MUTUAL FEDERADA"},
    {"codigo": "102", "nombre": "CORDOBA CON ELLAS"},
    {"codigo": "103", "nombre": "UNION PERSONAL"},
    {"codigo": "104", "nombre": "UNIMED"},
    {"codigo": "105", "nombre": "OSPPCYQ (PAPEL CARTON Y QUIMICOS)"},
    {"codigo": "106", "nombre": "IOSFA"},
    {"codigo": "124", "nombre": "PACIENTES CUIDADOS"},
    {"codigo": "249", "nombre": "OSPICAL"},
    {"codigo": "AMPIL", "nombre": "AMPIL"},
    {"codigo": "ANDINAART", "nombre": "ANDINA ART"},
    {"codigo": "APOS", "nombre": "APOS"},
    {"codigo": "APROSSDOCU", "nombre": "APROSS INSULINAS TIRAS DOCUFLEX"},
    {"codigo": "APROSSINS", "nombre": "APROSS INSULINAS TIRAS"},
    {"codigo": "APROSSMETA", "nombre": "APROSS TIRAS META"},
    {"codigo": "APROSSONCO", "nombre": "APROSS ONCOLOGICO"},
    {"codigo": "ASOCIARTAR", "nombre": "ASOCIART ART"},
    {"codigo": "ATEISUIZO", "nombre": "APROSS TIRAS E INSULINAS SUIZO"},
    {"codigo": "ATI20DEJUN", "nombre": "APROSS TIRAS E INSULINAS 20 DE JUNIO"},
    {"codigo": "CAMPROART", "nombre": "CAMINOS PROTEGIDOS ART"},
    {"codigo": "CARDINAL", "nombre": "CARDINAL ASSSITENCE"},
    {"codigo": "CEASANPEDR", "nombre": "CEA-SAN PEDRO"},
    {"codigo": "DASUTEN", "nombre": "DASUTEN"},
    {"codigo": "EA", "nombre": "EXPERIENCIA ART"},
    {"codigo": "EXPART", "nombre": "EXPERTA ART"},
    {"codigo": "GALENOART", "nombre": "GALENO ART"},
    {"codigo": "HPCBA", "nombre": "HOSPITAL PRIVADO CBA"},
    {"codigo": "IBEROASIST", "nombre": "IBERO ASISTENCIA"},
    {"codigo": "LIDERAR", "nombre": "LIDERAR ART"},
    {"codigo": "MAC", "nombre": "MAC"},
    {"codigo": "MEBA", "nombre": "MEBA"},
    {"codigo": "MERIDIOART", "nombre": "LA MERIDIONAL ART"},
    {"codigo": "MPN", "nombre": "MEDICAMENTOS DE PRIMER NIVEL"},
    {"codigo": "MUTRALART", "nombre": "MUTUAL RURAL ART"},
    {"codigo": "OMINTDIAB", "nombre": "OMINT DIABETICOS"},
    {"codigo": "OPDEA", "nombre": "OPDEA"},
    {"codigo": "OSADEF", "nombre": "OSADEF"},
    {"codigo": "OSEF", "nombre": "OSEF"},
    {"codigo": "OSETRA", "nombre": "OSETRA"},
    {"codigo": "OSIAOIT", "nombre": "OSITAC AOITA"},
    {"codigo": "OSPJN", "nombre": "OSPJN - PODER JUDICIAL"},
    {"codigo": "OSPRPA", "nombre": "OSPPRA"},
    {"codigo": "OSSACRA", "nombre": "OSSACRA"},
    {"codigo": "PAMIMANUAL", "nombre": "PAMI MANUAL"},
    {"codigo": "PAMIONCO", "nombre": "PAMI ONCOLOGIA"},
    {"codigo": "PAMIOSTOMI", "nombre": "PAMI OSTOMIA"},
    {"codigo": "PAMISUPL", "nombre": "PAMI SUPLEMENTOS NUTRICIONALES"},
    {"codigo": "PAMITDPA", "nombre": "PAMI TOMA DE PRESION"},
    {"codigo": "PAMIVACUNA", "nombre": "PAMI VACUNAS"},
    {"codigo": "PLAN1", "nombre": "."},
    {"codigo": "PLUSART", "nombre": "PLUS ART"},
    {"codigo": "PM10X30", "nombre": "PAMI PAÑALES"},
    {"codigo": "PROVART", "nombre": "PROVINCIA ART"},
    {"codigo": "SAPM", "nombre": "SIPSSA APM"},
    {"codigo": "SASSPE", "nombre": "SIPSSA ASSSPE"},
    {"codigo": "SEGUNDAART", "nombre": "LA SEGUNDA ART"},
    {"codigo": "SERENAART", "nombre": "SERENA ART"},
    {"codigo": "SERVP", "nombre": "SERVICI PENITENCIARIO FEDERAL"},
    {"codigo": "SIPALLEN36", "nombre": "SIPSSA ALLENDE 36"},
    {"codigo": "SIPALLENDE", "nombre": "SIPSSA ALLENDE"},
    {"codigo": "SIPOSACRAV", "nombre": "SIPSSA OSACRA V"},
    {"codigo": "SIPSSAAS", "nombre": "SIPSSA AS"},
    {"codigo": "SMGART", "nombre": "SMG ART"},
    {"codigo": "SOA", "nombre": "SIPSSA OSPOCE APEX"},
    {"codigo": "SOSCEP", "nombre": "SIPSSA OSCEP"},
    {"codigo": "SOSIM", "nombre": "SIPSSA OSIM"},
    {"codigo": "SOSPOCE", "nombre": "SIPSSA OSPOCE"},
    {"codigo": "SOSSACRA", "nombre": "SIPSSA OSSACRA"},
    {"codigo": "SP", "nombre": "SIPSSA PREPAGO"},
    {"codigo": "VICTORIART", "nombre": "VICTORIA ART"},
]


def run(session) -> None:
    for it in OBRAS_SOCIALES:
        codigo = (it["codigo"] or "").strip()
        nombre = (it["nombre"] or "").strip()

        if not codigo:
            continue

        obj = session.execute(
            select(ObraSocial).where(ObraSocial.codigo == codigo)
        ).scalar_one_or_none()

        if obj:
            obj.nombre = nombre
            obj.activo = True
            session.add(obj)
        else:
            session.add(ObraSocial(codigo=codigo, nombre=nombre, activo=True))
