"""se modificaron los modelos

Revision ID: 1b793087d51a
Revises: ef9f8a6e577d
Create Date: 2026-01-15 14:29:58.403302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b793087d51a'
down_revision: Union[str, Sequence[str], None] = 'ef9f8a6e577d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recepcion', 'numero',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('recepcion_numero_seq')"),
               existing_nullable=False)
    op.alter_column('recepcion', 'estado_recepcion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_recepcion_estado_recepcion'), table_name='recepcion')
    op.create_index('ix_recepcion_estado_recepcion_id', 'recepcion', ['estado_recepcion_id'], unique=False)
    op.drop_column('recepcion', 'estado_recepcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recepcion', sa.Column('estado_recepcion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_recepcion_estado_recepcion_id', table_name='recepcion')
    op.create_index(op.f('ix_recepcion_estado_recepcion'), 'recepcion', ['estado_recepcion'], unique=False)
    op.alter_column('recepcion', 'estado_recepcion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recepcion', 'numero',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('recepcion_numero_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
