"""se agrego un unqui en archivo_detalle

Revision ID: c750c673a271
Revises: 688a008bf4df
Create Date: 2026-03-10 08:13:35.015168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c750c673a271'
down_revision: Union[str, Sequence[str], None] = '688a008bf4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_archivo_detalle_archivo_cod_medic', 'archivo_detalle', ['archivo_id', 'cod_medic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_archivo_detalle_archivo_cod_medic', 'archivo_detalle', type_='unique')
    # ### end Alembic commands ###
