"""se agrego un nuevo estado para la receta para ver si fue auditada o no

Revision ID: d28ea0e2b20d
Revises: 5eb6b48e3930
Create Date: 2026-01-15 08:11:51.612570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28ea0e2b20d'
down_revision: Union[str, Sequence[str], None] = '5eb6b48e3930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recepcion', 'numero',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('recepcion_numero_seq')"),
               existing_nullable=False)
    op.add_column('recetas_historial', sa.Column('estado_receta', sa.String(), nullable=False))
    op.alter_column('recetas_historial', 'estado_seguimiento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recetas_historial', 'estado_seguimiento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recetas_historial', 'estado_receta')
    op.alter_column('recepcion', 'numero',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('recepcion_numero_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
