from __future__ import annotations

from app.application.carga_recepcion_application import CargaRecepcionApplication
from app.application.carga_recepcion_application import CloseRecepcionOut
from app.application.carga_recepcion_application import ListImagesOut
from app.application.carga_recepcion_application import LoadRecepcionOut
from app.application.carga_recepcion_application import ProcesarCargaIn
from app.application.carga_recepcion_application import ProcesarOut


class CargaRecepcionUseCase(CargaRecepcionApplication):
    pass
